const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "/images/item-1.jpeg",
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "/images/item-2.jpeg",
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "/images/item-3.jpeg",
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "/images/item-4.jpeg",
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch.`,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "/images/item-5.jpeg",
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "/images/item-6.jpeg",
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "/images/item-7.jpeg",
    desc: `carry jianbing normcore freegan viral single-origin coffee.`,
  },
  {
    id: 8,
    title: "american classic",
    category: "snacks",
    price: 12.99,
    img: "/images/item-8.jpeg",
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid.`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "/images/item-9.jpeg",
    desc: `skateboard fam synth authentic semiotics.`,
  },
    {
    id: 10,
    title: "spicy chicken wrap",
    category: "lunch",
    price: 14.99,
    img: "/images/item-10.png",
    desc: `grilled chicken wrap with spicy mayo, lettuce, tomatoes, and crispy onions.`,
  },
  {
    id: 11,
    title: "strawberry heaven",
    category: "shakes",
    price: 9.99,
    img: "/images/item-11.png",
    desc: `fresh strawberry milkshake topped with whipped cream and strawberry syrup.`,
  },
  {
    id: 12,
    title: "cheese burst burger",
    category: "lunch",
    price: 17.99,
    img: "/images/item-12.png",
    desc: `juicy beef burger loaded with melted cheddar cheese and smoky sauce.`,
  },
  {
    id: 13,
    title: "avocado toast",
    category: "breakfast",
    price: 11.99,
    img: "/images/item-13.png",
    desc: `crispy toast layered with smashed avocado, eggs, and chili flakes.`,
  },
  {
    id: 14,
    title: "chocolate volcano",
    category: "shakes",
    price: 10.99,
    img: "/images/item-14.png",
    desc: `rich chocolate shake with brownie chunks and dark chocolate drizzle.`,
  },
  {
    id: 15,
    title: "veggie supreme pizza",
    category: "dinner",
    price: 24.99,
    img: "/images/item-15.png",
    desc: `loaded veggie pizza with olives, peppers, onions, and mozzarella cheese.`,
  },
  {
    id: 16,
    title: "bbq wings",
    category: "dinner",
    price: 19.99,
    img: "/images/item-16.png",
    desc: `crispy chicken wings coated in smoky barbecue sauce with ranch dip.`,
  },
  {
    id: 17,
    title: "banana caramel shake",
    category: "shakes",
    price: 8.99,
    img: "/images/item-17.png",
    desc: `smooth banana shake blended with caramel syrup and cookie crumbs.`,
  },
  {
    id: 18,
    title: "loaded fries",
    category: "snacks",
    price: 7.99,
    img: "/images/item-18.png",
    desc: `crispy fries topped with cheese sauce, jalapeños, and herbs.`,
  },
  {
    id: 19,
    title: "grilled salmon",
    category: "dinner",
    price: 28.99,
    img: "/images/item-19.png",
    desc: `perfectly grilled salmon served with garlic butter and vegetables.`,
  },
  {
    id: 20,
    title: "classic waffles",
    category: "breakfast",
    price: 13.99,
    img: "/images/item-20.png",
    desc: `golden waffles topped with maple syrup, butter, and fresh berries.`,
  }
];

export default menu;
